### ISSUE TITLE
Car racing and quadratic constraint

### ISSUE THREAD

**Issue by Zhenyu-Li** [HybridRobotics/MPC-CBF#1]
Hi, Mr. Zeng

Thanks for your contributions.  I have some questions about this code.
It seems that the CBF constraint is quadratic constraint w.r.t. the u. So what kind of solver do you use? (sorry I am not familiar with MATLAB solver.) Is there any Python solver for this kind of optimization problem?   Btw, will you share the code for car racing case?

Thanks a lot.

**Comment by junzengx14** [comment]
Yes, the control barrier function is **quadratic** to system state x in our double integrator example and is **quartic** to system state x in our car racing example. We usually say too much about the CBF constraint w.r.t to system input u, but for our case, the $x_{k+1}$ is linear with respect to $u_k$ and CBF is quadratic w.r.t to $x_{k+1}$, we could probably call that CBF is quadratic constraint (I mean at most two order) w.r.t u.

Notice that when control barrier function is linear to the state, our CBF constraint will be **linear** w.r.t u.

In Matlab, I use Ipopt solver with [Yalmip](https://yalmip.github.io/) as modelling language. In python, I use Ipopt solver with [casadi](https://web.casadi.org/) as modelling language. I included Ipopt solver with MATLAB interface in this repo already if you want to try that.

For your last question, as I mentioned in readme, we will release car racing code after the paper is accepted.

**Comment by junzengx14** [comment]
I'm moving the car racing part of this repo as it might not looks great with both matlab and python in one repo, and will notify you when my repo of car racing becomes public.

**Comment by qinlincmu** [comment]
I comment here just for timely notification of the upcoming release of the car racing example. Very interesting work!

**Comment by junzengx14** [comment]
> I comment here just for timely notification of the upcoming release of the car racing example. Very interesting work!

Thanks Qin, will notify you soon later :)

**Comment by junzengx14** [comment]
Car racing numerical examples will be moved to this [repo](https://github.com/HybridRobotics/Car-Racing).

The code will be shown there and this issue will be closed after I upload all code there.

**Comment by junzengx14** [comment]
A quasi-complete version of the code is uploaded in the link. @Zhenyu-Li  @qinlincmu

**Comment by junzengx14** [comment]
@Zhenyu-Li I updated the name of PR in case of other people having the same confuse, hope you don't mind.
